/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyHistoryRouteImport } from './routes/my-history'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GamesRouteImport } from './routes/games'
import { Route as CreateTeamRouteImport } from './routes/create-team'
import { Route as CreateMatchRouteImport } from './routes/create-match'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentTournamentIdRouteImport } from './routes/tournament/$tournamentId'
import { Route as MatchMatchIdRouteImport } from './routes/match/$matchId'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyHistoryRoute = MyHistoryRouteImport.update({
  id: '/my-history',
  path: '/my-history',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTeamRoute = CreateTeamRouteImport.update({
  id: '/create-team',
  path: '/create-team',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateMatchRoute = CreateMatchRouteImport.update({
  id: '/create-match',
  path: '/create-match',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentTournamentIdRoute = TournamentTournamentIdRouteImport.update({
  id: '/tournament/$tournamentId',
  path: '/tournament/$tournamentId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/create-match': typeof CreateMatchRoute
  '/create-team': typeof CreateTeamRoute
  '/games': typeof GamesRoute
  '/history': typeof HistoryRoute
  '/my-history': typeof MyHistoryRoute
  '/profile': typeof ProfileRoute
  '/teams': typeof TeamsRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/tournament/$tournamentId': typeof TournamentTournamentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/create-match': typeof CreateMatchRoute
  '/create-team': typeof CreateTeamRoute
  '/games': typeof GamesRoute
  '/history': typeof HistoryRoute
  '/my-history': typeof MyHistoryRoute
  '/profile': typeof ProfileRoute
  '/teams': typeof TeamsRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/tournament/$tournamentId': typeof TournamentTournamentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/create-match': typeof CreateMatchRoute
  '/create-team': typeof CreateTeamRoute
  '/games': typeof GamesRoute
  '/history': typeof HistoryRoute
  '/my-history': typeof MyHistoryRoute
  '/profile': typeof ProfileRoute
  '/teams': typeof TeamsRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/tournament/$tournamentId': typeof TournamentTournamentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/create-match'
    | '/create-team'
    | '/games'
    | '/history'
    | '/my-history'
    | '/profile'
    | '/teams'
    | '/match/$matchId'
    | '/tournament/$tournamentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/create-match'
    | '/create-team'
    | '/games'
    | '/history'
    | '/my-history'
    | '/profile'
    | '/teams'
    | '/match/$matchId'
    | '/tournament/$tournamentId'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/create-match'
    | '/create-team'
    | '/games'
    | '/history'
    | '/my-history'
    | '/profile'
    | '/teams'
    | '/match/$matchId'
    | '/tournament/$tournamentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  CreateMatchRoute: typeof CreateMatchRoute
  CreateTeamRoute: typeof CreateTeamRoute
  GamesRoute: typeof GamesRoute
  HistoryRoute: typeof HistoryRoute
  MyHistoryRoute: typeof MyHistoryRoute
  ProfileRoute: typeof ProfileRoute
  TeamsRoute: typeof TeamsRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  TournamentTournamentIdRoute: typeof TournamentTournamentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-history': {
      id: '/my-history'
      path: '/my-history'
      fullPath: '/my-history'
      preLoaderRoute: typeof MyHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-team': {
      id: '/create-team'
      path: '/create-team'
      fullPath: '/create-team'
      preLoaderRoute: typeof CreateTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-match': {
      id: '/create-match'
      path: '/create-match'
      fullPath: '/create-match'
      preLoaderRoute: typeof CreateMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/$tournamentId': {
      id: '/tournament/$tournamentId'
      path: '/tournament/$tournamentId'
      fullPath: '/tournament/$tournamentId'
      preLoaderRoute: typeof TournamentTournamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  CreateMatchRoute: CreateMatchRoute,
  CreateTeamRoute: CreateTeamRoute,
  GamesRoute: GamesRoute,
  HistoryRoute: HistoryRoute,
  MyHistoryRoute: MyHistoryRoute,
  ProfileRoute: ProfileRoute,
  TeamsRoute: TeamsRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  TournamentTournamentIdRoute: TournamentTournamentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
