/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CreateTeamRouteImport } from './routes/create-team'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentTournamentIdRouteImport } from './routes/tournament/$tournamentId'
import { Route as MatchMatchIdRouteImport } from './routes/match/$matchId'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTeamRoute = CreateTeamRouteImport.update({
  id: '/create-team',
  path: '/create-team',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentTournamentIdRoute = TournamentTournamentIdRouteImport.update({
  id: '/tournament/$tournamentId',
  path: '/tournament/$tournamentId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/create-team': typeof CreateTeamRoute
  '/history': typeof HistoryRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/tournament/$tournamentId': typeof TournamentTournamentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/create-team': typeof CreateTeamRoute
  '/history': typeof HistoryRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/tournament/$tournamentId': typeof TournamentTournamentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/create-team': typeof CreateTeamRoute
  '/history': typeof HistoryRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/tournament/$tournamentId': typeof TournamentTournamentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/create-team'
    | '/history'
    | '/match/$matchId'
    | '/tournament/$tournamentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/create-team'
    | '/history'
    | '/match/$matchId'
    | '/tournament/$tournamentId'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/create-team'
    | '/history'
    | '/match/$matchId'
    | '/tournament/$tournamentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  CreateTeamRoute: typeof CreateTeamRoute
  HistoryRoute: typeof HistoryRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  TournamentTournamentIdRoute: typeof TournamentTournamentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-team': {
      id: '/create-team'
      path: '/create-team'
      fullPath: '/create-team'
      preLoaderRoute: typeof CreateTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/$tournamentId': {
      id: '/tournament/$tournamentId'
      path: '/tournament/$tournamentId'
      fullPath: '/tournament/$tournamentId'
      preLoaderRoute: typeof TournamentTournamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  CreateTeamRoute: CreateTeamRoute,
  HistoryRoute: HistoryRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  TournamentTournamentIdRoute: TournamentTournamentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
